# Generated by Django 4.1.7 on 2023-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('cant_temp', models.TextField(max_length=3)),
                ('resumen', models.TextField(max_length=100)),
                ('puntaje', models.TextField(max_length=3)),
            ],
        ),
    ]
