# Generated by Django 4.1.7 on 2023-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top_Series', '0002_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proximas_Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proxima_serie', models.TextField(max_length=50)),
                ('fecha_lanzamiento', models.DateTimeField()),
            ],
        ),
    ]
