# Generated by Django 4.1.7 on 2023-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top_Series', '0004_alter_proximas_series_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximas_series',
            name='fecha_lanzamiento',
            field=models.TextField(max_length=20),
        ),
    ]
