# Generated by Django 4.1.7 on 2023-04-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_principal', models.CharField(max_length=30)),
                ('cantidad_de_temporadas', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
