# Generated by Django 4.1.7 on 2023-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_juegos_publisher_alter_juegos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos'),
        ),
    ]
